name: build & sign & publish
on:
  push:
    branches:
      - master
jobs:
  compare-version:
    name: Compare version
    runs-on: ubuntu-latest
    outputs:
      newVersion: ${{ steps.read-committed-version.outputs.newVersion }}
      isDifferent: ${{ steps.compare-version.outputs.isDifferent }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
        # uses: actions/checkout@master

      - name: "Open committed manifest"
        id: open-committed-manifest
        uses: juliangruber/read-file-action@v1
        with:
          path: "./manifest.json"

      - name: "Read committed version"
        id: read-committed-version
        run: echo "::set-output name=newVersion::v${{ fromJson(steps.open-committed-manifest.outputs.content).version }}"

      - name: "Read latest release version"
        id: read-latest-release-version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}

      - name: "Compare version"
        id: compare-version
        run: |
          echo "Committed version is ${newVersion}, latest release version is ${oldVersion}"
          if [ ${newVersion} = ${oldVersion} ]; then
            echo "They are identical"
            echo "::set-output name=isDifferent::false"
          else
            echo "They are different"
            echo "::set-output name=isDifferent::true"
          fi
        env:
          newVersion: ${{ steps.read-committed-version.outputs.newVersion }}
          oldVersion: ${{ steps.read-latest-release-version.outputs.tag }}

  publish-to-github:
    name: Publish to Github
    needs: compare-version
    if: ${{ needs.compare-version.outputs.isDifferent }}
    outputs:
      pathXPI: ${{ steps.web-ext-sign.outputs.target }}
      version: ${{ needs.compare-version.outputs.newVersion }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .

      - name: "Sign"
        id: web-ext-sign
        uses: chenxian352/action-web-ext@master
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.MOZILLA_API_SABINE_USER }}
          apiSecret: ${{ secrets.MOZILLA_API_SABINE_SECRET }}
          timeout: 600000 # 10 minutes

      - name: "Create Release"
        if: steps.web-ext-sign.result == 'success' # must use single quotes for string literals
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.web-ext-sign.outputs.target }}
          tag_name: ${{ needs.compare-version.outputs.newVersion }}
          name: Release ${{ needs.compare-version.outputs.newVersion }}

  commit-path-to-updates:
    name: Commit path for update
    needs: publish-to-github
    if: ${{ needs.publish-to-github.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Modify updates.json"
        shell: python3
        env:
          JSONPATH: './updates.json'
          XPIVERSION: ${{ needs.publish-to-github.outputs.version }}
          XPIPATH: ${{ needs.publish-to-github.outputs.pathXPI }}
          ADDONID: '{212d2e80-11e9-4876-a063-b544b093bb47}'
        run: |
          import json
          import os
          data = json.load(open(os.getenv('JSONPATH'), 'r'))
          newupd = {
            "version": os.getenv('XPIVERSION'),
            "update_link": os.getenv('XPIPATH')
          }
          data['addons'][os.getenv('ADDONID')]['updates'].append(newupd)
          json.dump(data, open(os.getenv('JSONPATH'), 'w'), indent='\t')

      - name: "Commit"
        run: |
          git add ./updates.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Auto-commit: make XPI path available to updates"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
