name: Builds and signs the WebExtension
on:
  push:
    branches:
      - master
jobs:
  publish-to-github:
    name: Build and package the extension
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v1
        # uses: actions/checkout@master

      - name: "Build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .

      - name: "Sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.MOZILLA_API_SABINE_USER }}
          apiSecret: ${{ secrets.MOZILLA_API_SABINE_SECRET }}
         # WEB_EXT_ID: "{212d2e80-11e9-4876-a063-b544b093bb47}"
#        uses: saphareas/sign-web-extension-action@master
#        with:
#          web-ext-id: "{212d2e80-11e9-4876-a063-b544b093bb47}"
#          sign-listed: false
#          amo-api-key: ${{ secrets.MOZILLA_API_SABINE_USER }}
#          amo-api-secret: ${{ secrets.MOZILLA_API_SABINE_SECRET }}

      - name: "Create Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.web-ext-sign.outputs.target }}
#        uses: actions/create-release@v1
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: false
#          prerelease: true
        # if: SIGNING-WAS-SUCCESSFUL
        # if: startsWith(github.ref, 'refs/tags/')

#       - name: Upload Release Asset
#         id: upload-release-asset
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
# #          asset_path: ./terra-snellman.zip
#           asset_name: terra-snellman.xpi
#           asset_content_type: application/zip
