name: Builds and signs the WebExtension
on:
  push:
    branches:
      - master
jobs:
  compare-version:
    name: Compare version
    runs-on: ubuntu-latest
    outputs:
      newVersion: ${{ steps.read-committed-version.outputs.version }}
        description: "The value of this commit's version number"
      isDifferent: ${{ steps.compare-version.outputs.isDifferent }}
        description: "Boolean whether this commit contains a version number different from the latest release"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
        # uses: actions/checkout@master

      - name: "Read committed version"
        id: read-committed-version
        uses: tyankatsu0105/read-package-version-actions@v1
        with:
          path: "./manifest.json"

      - name: "Read latest release version"
        id: read-latest-release-version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            repository: ${{ github.repository }}

      - name: "Compare version"
        id: compare-version
        run: |
          echo "Committed version is ${{ newVersion }}, latest release version is ${{ oldVersion }}"
          echo "Are they different?"
          $different = [ ${{ newVersion }} = ${{ oldVersion }} ]
          echo ${different}
          echo "::set-output name=isDifferent::${{ different }}"
          echo "::set-output name=newVersion::${{ newVersion }}"
        with:
          newVersion: ${{ steps.read-committed-version.outputs.version }}
          oldVersion: ${{ steps.read-latest-release-version.outputs.release }}

  publish-to-github:
    name: Publish to Github
    needs: compare-version
    # if: ${{ needs.compare-version.outputs.isDifferent }}
    runs-on: ubuntu-latest
    steps:
      - name: "Test output"
        run: |
          echo "new version=${{ needs.compare-version.outputs.newVersion }}, is different=${{ needs.compare-version.outputs.isDifferent }}"

      - name: "Test boolean"
        if: ${{ needs.compare-version.outputs.isDifferent }}
        run: echo "yes different!"

      - name: "Checkout"
        if: false
        uses: actions/checkout@v1

      - name: "Build"
        if: false
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .

      - name: "Sign"
        if: false
        id: web-ext-sign
        # uses: kewisch/action-web-ext@v1
        # with:
        #   cmd: sign
        #   source: ${{ steps.web-ext-build.outputs.target }}
        #   channel: unlisted
        #   apiKey: ${{ secrets.MOZILLA_API_SABINE_USER }}
        #   apiSecret: ${{ secrets.MOZILLA_API_SABINE_SECRET }}
        uses: saphareas/sign-web-extension-action@master
        with:
          web-ext-id: "{212d2e80-11e9-4876-a063-b544b093bb47}"
          sign-listed: false
          amo-api-key: ${{ secrets.MOZILLA_API_SABINE_USER }}
          amo-api-secret: ${{ secrets.MOZILLA_API_SABINE_SECRET }}

      - name: "Create Release"
        if: false && steps.web-ext-sign.conclusion == 'success' # must use single quotes for string literals
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.web-ext-sign.outputs.target }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}

#        uses: actions/create-release@v1
#          release_name: Release ${{ github.ref }}
#          tag_name: ${{ github.ref }}
#          draft: false
#          prerelease: true
        # if: SIGNING-WAS-SUCCESSFUL
        # if: startsWith(github.ref, 'refs/tags/')

#       - name: Upload Release Asset
#         id: upload-release-asset
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
# #          asset_path: ./terra-snellman.zip
#           asset_name: terra-snellman.xpi
#           asset_content_type: application/zip
